### ISSUE TITLE
ADC @  GND jumps between 0 and 255

### ISSUE THREAD

**Issue by hexxter** [DFRobot/DFRobot_RaspberryPi_Expansion_Board#2]
If i use adc example on rpi4 and short the ADC to GND it always jumps between 0 and 255

**Comment by hexxter** [comment]
i think its a bug in the stm firmware.

rslt =

[0, 0]

[0, 0]

[0, 255]

[0, 255]

[0, 0]

[0, 0]

[0, 0]

**Comment by hexxter** [comment]
i found the problem you must disable rasperry pi audio in /boot/config.txt

**Comment by Arya11111** [comment]
Thanks
